modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"
logoFile = "icon.png"

[[dependencies.factory_api]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.factory_api]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.factory_api]]
modId = "architectury"
mandatory = true
versionRange = "[4.4.68,)"
ordering = "AFTER"
side = "BOTH"