import io.ktor.util.collections.setValue

plugins {
	id("mod-platform")
	id("net.minecraftforge.gradle")
	id("net.minecraftforge.renamer") version "1.0.14"
}

platform {
	loader = "forge"
	dependencies {
		required("minecraft") {
			forgeVersionRange = "[${prop("mc_version_range")}]"
		}
		required("forge") {
			forgeVersionRange = "[1,)"
		}
	}
}

if (stonecutter.eval(stonecutter.current.version, "<1.20.5")) {

	renamer.enableMixinRefmaps {
		// Test source set SHOULDN'T be used for the refmaps (circular dependencies with kotlin for some reason)
		config("${prop("mod_id")}.mixins.json")
		source(sourceSets.main.get(), prop("mod_id"))
		jar(project.tasks.named(JavaPlugin.JAR_TASK_NAME, Jar::class.java))
	}

	afterEvaluate {
		minecraft.runs.forEach { r ->
			renamer.mixin.run(r)
		}
	}

	renamer.classes(tasks.named<Jar>("jar")) {
		map.from(minecraft.dependency.toSrgFile)
		archiveClassifier = "srg"
		// We need to use the generated mappings, which includes things generated by the annotation processor
		mappings(renamer.mixin.generatedMappings)
	}
}

minecraft {
	mappings("official", stonecutter.current.version)

	version = "${stonecutter.current.version}-${property("forge_version")}"

	//validateAccessTransformers = true

	accessTransformers = files(project.file(platform.atFile))

	runs {
		configureEach {
			workingDir.convention(layout.projectDirectory.dir("run"))
		}

		register("client") {
			systemProperty("forge.enabledGameTestNamespaces", prop("mod_id"))
			args("--mixin.config", "${prop("mod_id")}.mixins.json")
//			client()
//			gameDirectory = file("run/")
//			ideName = "Forge Client (${stonecutter.active?.version})"
//			programArgument("--username=Dev")
		}
		register("server") {
//			server()
//			gameDirectory = file("run/")
//			ideName = "Forge Server (${stonecutter.active?.version})"
		}
	}


//	mods {
//		register(prop("mod_id")) {
//			sourceSet(sourceSets["main"])
//		}
//	}
}

repositories {
	mavenCentral()
	minecraft.mavenizer(this) // In Kotlin, it = this
	maven(fg.forgeMaven)
	maven(fg.minecraftLibsMaven)
	strictMaven("https://api.modrinth.com/maven", "maven.modrinth") { name = "Modrinth" }
}

dependencies {
	implementation(minecraft.dependency("net.minecraftforge:forge:${stonecutter.current.version}-${prop("forge_version")}"))
	annotationProcessor("org.spongepowered:mixin:${libs.versions.mixin.get()}:processor")

	//implementation(libs.moulberry.mixinconstraints)
	compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0") as Any)

}

if (stonecutter.eval(stonecutter.current.version, "<1.20.5")) {
	renamer.mappings(minecraft.dependency.toSrg)
}

sourceSets {
	main {
		resources.srcDir(
			"${rootDir}/versions/datagen/${stonecutter.current.version.split("-")[0]}/src/main/generated"
		)
	}
}

tasks.withType<Javadoc> {
	enabled = false
}

//tasks.named("createMinecraftArtifacts") {
//	dependsOn(tasks.named("stonecutterGenerate"))
//}