modLoader = "javafml"
loaderVersion = "[${forge_version},)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_source}"
logoFile="logo.png"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version_range}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "factocrafty"
mandatory = false
versionRange = "[0.0.0.4,)"
ordering = "AFTER"
side = "BOTH"